"""
JavaScript code generator for Z-Machine

Generates optimized JavaScript code from Z-Machine bytecode
"""

import base64
import json
from typing import List, Dict, Any, Optional
from zparser import ZParser, ZHeader
from opcodes import OpcodeDecoder, Instruction


class JavaScriptGenerator:
    """Generate JavaScript from Z-Machine bytecode"""

    def __init__(self, parser: ZParser):
        self.parser = parser
        self.decoder = OpcodeDecoder(parser.memory, parser.header.version)
        self.routines = {}  # Discovered routines
        self.strings = {}   # String literals

    def generate(self) -> str:
        """Generate complete JavaScript module"""
        sections = [
            self._generate_header(),
            self._generate_constants(),
            self._generate_runtime(),
            self._generate_memory(),
            self._generate_opcodes(),
            self._generate_routines(),
            self._generate_main(),
            self._generate_exports()
        ]

        return "\n\n".join(sections)

    def _generate_header(self) -> str:
        """Generate file header with metadata"""
        return f'''/**
 * Z-Machine JavaScript Runtime
 * Generated by z2js compiler
 *
 * Story: {self.parser.header.serial}
 * Z-Machine Version: {self.parser.header.version}
 * Release: {self.parser.header.release}
 */

"use strict";'''

    def _generate_constants(self) -> str:
        """Generate constants from header"""
        h = self.parser.header
        return f'''// Z-Machine Constants
const VERSION = {h.version};
const INITIAL_PC = 0x{h.initial_pc:04X};
const DICTIONARY_ADDR = 0x{h.dictionary:04X};
const OBJECT_TABLE_ADDR = 0x{h.object_table:04X};
const GLOBALS_ADDR = 0x{h.globals:04X};
const STATIC_MEMORY = 0x{h.static_memory:04X};
const ABBREVIATIONS_ADDR = 0x{h.abbreviations:04X};
const HIGH_MEMORY = 0x{h.high_memory:04X};'''

    def _generate_runtime(self) -> str:
        """Generate the Z-Machine runtime system"""
        return '''// Z-Machine Runtime
class ZMachine {
    constructor(storyData) {
        // Memory
        this.memory = new Uint8Array(storyData);
        this.originalMemory = new Uint8Array(storyData);

        // CPU state
        this.pc = INITIAL_PC;
        this.stack = [];
        this.callStack = [];
        this.locals = new Array(16);

        // I/O
        this.outputBuffer = "";
        this.statusLine = { location: "", score: 0, turns: 0 };
        this.windows = [{ text: "", cursor: [1, 1] }, { text: "", cursor: [1, 1] }];
        this.currentWindow = 0;

        // Interpreter state
        this.running = false;
        this.finished = false;
        this.inputCallback = null;
        this.outputCallback = null;
        this.saveCallback = null;
        this.restoreCallback = null;

        // Random state
        this.randomMode = "random";
        this.randomSeed = 0;
        this.randomIndex = 0;

        // Debug state
        this.debugMode = false;  // Enable debug to trace instructions (set to true to enable)
        this.instructionCount = 0;
        this.instructionHistory = [];
        this.maxHistorySize = 100;
    }

    // Memory access
    readByte(addr) {
        return this.memory[addr];
    }

    readWord(addr) {
        return (this.memory[addr] << 8) | this.memory[addr + 1];
    }

    writeByte(addr, value) {
        if (addr >= STATIC_MEMORY) {
            throw new Error(`[WRITE PROTECTION] Attempted to write byte to read-only memory at 0x${addr.toString(16)} (value=0x${value.toString(16)}, static memory starts at 0x${STATIC_MEMORY.toString(16)})`);
        }
        const oldValue = this.memory[addr];
        this.memory[addr] = value & 0xFF;
        if (this.debugMode) {
            console.error(`[WRITE #${this.instructionCount}] @0x${addr.toString(16).padStart(4,'0')} byte 0x${oldValue.toString(16).padStart(2,'0')} -> 0x${(value & 0xFF).toString(16).padStart(2,'0')}`);
        }
    }

    writeWord(addr, value) {
        if (addr >= STATIC_MEMORY) {
            throw new Error(`[WRITE PROTECTION] Attempted to write word to read-only memory at 0x${addr.toString(16)} (value=0x${value.toString(16)}, static memory starts at 0x${STATIC_MEMORY.toString(16)})`);
        }
        const oldValue = this.readWord(addr);
        this.memory[addr] = (value >> 8) & 0xFF;
        this.memory[addr + 1] = value & 0xFF;
        if (this.debugMode) {
            console.error(`[WRITE #${this.instructionCount}] @0x${addr.toString(16).padStart(4,'0')} word 0x${oldValue.toString(16).padStart(4,'0')} -> 0x${(value & 0xFFFF).toString(16).padStart(4,'0')}`);
        }
    }

    // Stack operations
    push(value) {
        this.stack.push(value & 0xFFFF);
    }

    pop() {
        if (this.stack.length === 0) {
            throw new Error("Stack underflow");
        }
        return this.stack.pop();
    }

    peek() {
        if (this.stack.length === 0) {
            throw new Error("Stack underflow");
        }
        return this.stack[this.stack.length - 1];
    }

    // Variable access (0=stack, 1-15=locals, 16+=globals)
    getVariable(varNum) {
        if (varNum === 0) {
            return this.pop();
        } else if (varNum < 16) {
            return this.locals[varNum - 1] || 0;
        } else {
            const addr = GLOBALS_ADDR + (varNum - 16) * 2;
            return this.readWord(addr);
        }
    }

    setVariable(varNum, value) {
        value = value & 0xFFFF;
        if (varNum === 0) {
            this.push(value);
        } else if (varNum < 16) {
            this.locals[varNum - 1] = value;
        } else {
            const addr = GLOBALS_ADDR + (varNum - 16) * 2;
            this.writeWord(addr, value);
        }
    }

    // Operand evaluation
    getOperand(operand) {
        if (Array.isArray(operand) && operand[0] === "var") {
            return this.getVariable(operand[1]);
        }
        return operand;
    }

    // Packed address conversion
    unpackAddress(packed, isString = false) {
        switch (VERSION) {
            case 1: case 2: case 3:
                return packed * 2;
            case 4: case 5:
                return packed * 4;
            case 6: case 7:
                // TODO: Handle routine/string offsets
                return packed * 4;
            case 8:
                return packed * 8;
            default:
                return packed * 2;
        }
    }

    // Z-String decoding
    decodeZString(addr) {
        const startAddr = addr;
        // A2 alphabet varies by version - V1 has different punctuation
        // Spec section 3: A2 has space, newline, digits, then punctuation
        const a2_v1 = " 0123456789.,!?_#'\\"/<-:()";  // V1: has < instead of newline
        const a2_v2plus = " \\n0123456789.,!?_#'\\\"/\\\\-:()";  // V2+: correct order per spec

        const alphabets = [
            "abcdefghijklmnopqrstuvwxyz",      // A0 (default)
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ",      // A1
            VERSION === 1 ? a2_v1 : a2_v2plus  // A2 (version-specific)
        ];

        let result = "";
        let alphabet = 0;
        let abbrev = 0;
        let zsciiHigh = -1;  // For 10-bit ZSCII character codes

        while (true) {
            const word = this.readWord(addr);
            addr += 2;

            const chars = [
                (word >> 10) & 0x1F,
                (word >> 5) & 0x1F,
                word & 0x1F
            ];

            for (let c of chars) {

                if (zsciiHigh === -2) {
                    // This is the high 5 bits of ZSCII code
                    zsciiHigh = c;
                } else if (zsciiHigh >= 0) {
                    // This is the low 5 bits - combine with high to get full ZSCII
                    const zsciiCode = (zsciiHigh << 5) | c;
                    result += String.fromCharCode(zsciiCode);
                    zsciiHigh = -1;
                    alphabet = 0;
                } else if (abbrev > 0) {
                    // Handle abbreviation
                    if (VERSION >= 2 && ABBREVIATIONS_ADDR) {
                        const abbrevAddr = ABBREVIATIONS_ADDR + 2 * (32 * (abbrev - 1) + c);
                        const wordAddr = this.readWord(abbrevAddr);
                        result += this.decodeZString(wordAddr * 2);
                    }
                    abbrev = 0;
                } else if (c === 0) {
                    result += " ";
                } else if (c >= 1 && c <= 3 && VERSION >= 2) {
                    abbrev = c;
                } else if (c === 4) {
                    alphabet = 1;
                } else if (c === 5) {
                    alphabet = 2;
                } else if (c === 6 && alphabet === 2) {
                    // Start of 10-bit ZSCII code - next TWO characters form the code
                    zsciiHigh = -2;  // Marker that next char is high bits
                    // Don't reset alphabet yet
                } else if (c >= 6) {
                    const idx = c - 6;
                    let ch = null;
                    if (alphabet === 0 && idx < alphabets[0].length) {
                        ch = alphabets[0][idx];
                    } else if (alphabet === 1 && idx < alphabets[1].length) {
                        ch = alphabets[1][idx];
                    } else if (alphabet === 2 && idx < alphabets[2].length) {
                        ch = alphabets[2][idx];
                    }
                    if (ch !== null) result += ch;
                    alphabet = 0;
                }
            }

            if (word & 0x8000) break;
        }

        return result;
    }

    // Object system
    getObject(objNum) {
        if (objNum === 0) return null;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9;
            return {
                attributes: this.readWord(objAddr) << 16 | this.readWord(objAddr + 2),
                parent: this.readByte(objAddr + 4),
                sibling: this.readByte(objAddr + 5),
                child: this.readByte(objAddr + 6),
                properties: this.readWord(objAddr + 7)
            };
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14;
            return {
                attributes: this.readWord(objAddr) << 32 | this.readWord(objAddr + 2) << 16 |
                           this.readWord(objAddr + 4),
                parent: this.readWord(objAddr + 6),
                sibling: this.readWord(objAddr + 8),
                child: this.readWord(objAddr + 10),
                properties: this.readWord(objAddr + 12)
            };
        }
    }

    setObjectParent(objNum, parentNum) {
        if (objNum === 0) return;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9 + 4;
            this.writeByte(objAddr, parentNum);
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14 + 6;
            this.writeWord(objAddr, parentNum);
        }
    }

    setObjectSibling(objNum, siblingNum) {
        if (objNum === 0) return;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9 + 5;
            this.writeByte(objAddr, siblingNum);
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14 + 8;
            this.writeWord(objAddr, siblingNum);
        }
    }

    setObjectChild(objNum, childNum) {
        if (objNum === 0) return;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9 + 6;
            this.writeByte(objAddr, childNum);
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14 + 10;
            this.writeWord(objAddr, childNum);
        }
    }

    testAttribute(objNum, attrNum) {
        if (objNum === 0) return false;

        const obj = this.getObject(objNum);
        if (VERSION <= 3) {
            return !!(obj.attributes & (1 << (31 - attrNum)));
        } else {
            return !!(obj.attributes & (1 << (47 - attrNum)));
        }
    }

    setAttribute(objNum, attrNum) {
        if (objNum === 0) return;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9;
            const byteNum = Math.floor(attrNum / 8);
            const bitNum = 7 - (attrNum % 8);
            const b = this.readByte(objAddr + byteNum);
            this.writeByte(objAddr + byteNum, b | (1 << bitNum));
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14;
            const byteNum = Math.floor(attrNum / 8);
            const bitNum = 7 - (attrNum % 8);
            const b = this.readByte(objAddr + byteNum);
            this.writeByte(objAddr + byteNum, b | (1 << bitNum));
        }
    }

    clearAttribute(objNum, attrNum) {
        if (objNum === 0) return;

        let objAddr;
        if (VERSION <= 3) {
            objAddr = OBJECT_TABLE_ADDR + 62 + (objNum - 1) * 9;
            const byteNum = Math.floor(attrNum / 8);
            const bitNum = 7 - (attrNum % 8);
            const b = this.readByte(objAddr + byteNum);
            this.writeByte(objAddr + byteNum, b & ~(1 << bitNum));
        } else {
            objAddr = OBJECT_TABLE_ADDR + 126 + (objNum - 1) * 14;
            const byteNum = Math.floor(attrNum / 8);
            const bitNum = 7 - (attrNum % 8);
            const b = this.readByte(objAddr + byteNum);
            this.writeByte(objAddr + byteNum, b & ~(1 << bitNum));
        }
    }

    // Output functions
    print(text) {
        this.outputBuffer += text;
        if (this.outputCallback) {
            this.outputCallback(text);
        }
    }

    printNum(num) {
        // Handle signed 16-bit numbers
        if (num > 32767) {
            num = num - 65536;
        }
        this.print(num.toString());
    }

    printChar(charCode) {
        if (charCode === 13) {
            this.print("\\n");
        } else {
            this.print(String.fromCharCode(charCode));
        }
    }

    newLine() {
        this.print("\\n");
    }

    // Random number generation
    random(range) {
        if (range <= 0) {
            // Seed the generator
            this.randomSeed = -range;
            this.randomMode = "predictable";
            this.randomIndex = 0;
            return 0;
        }

        if (this.randomMode === "predictable") {
            // Simple predictable sequence
            this.randomIndex = (this.randomIndex * 1103515245 + 12345) & 0x7FFFFFFF;
            return (this.randomIndex % range) + 1;
        } else {
            return Math.floor(Math.random() * range) + 1;
        }
    }

    // Game state
    save() {
        if (this.saveCallback) {
            const state = {
                memory: Array.from(this.memory.slice(0, STATIC_MEMORY)),
                stack: this.stack.slice(),
                callStack: this.callStack.map(frame => ({
                    returnPC: frame.returnPC,
                    locals: frame.locals.slice(),
                    numLocals: frame.numLocals,
                    storeVar: frame.storeVar
                })),
                pc: this.pc,
                locals: this.locals.slice()
            };
            return this.saveCallback(state);
        }
        return false;
    }

    restore(state) {
        if (state && state.memory) {
            // Restore dynamic memory
            for (let i = 0; i < state.memory.length; i++) {
                this.memory[i] = state.memory[i];
            }
            this.stack = state.stack.slice();
            this.callStack = state.callStack.map(frame => ({
                returnPC: frame.returnPC,
                locals: frame.locals.slice(),
                numLocals: frame.numLocals,
                storeVar: frame.storeVar
            }));
            this.pc = state.pc;
            this.locals = state.locals.slice();
            return true;
        }
        return false;
    }

    restart() {
        // Restore original memory
        this.memory = new Uint8Array(this.originalMemory);
        this.pc = INITIAL_PC;
        this.stack = [];
        this.callStack = [];
        this.locals = new Array(16);
        this.outputBuffer = "";
        this.running = true;
        this.finished = false;
    }

    quit() {
        this.running = false;
        this.finished = true;
        this.print("\\n[Game terminated]\\n");
    }

    // Object name lookup
    getObjectName(objNum) {
        const obj = this.getObject(objNum);
        if (!obj) return "";

        let propAddr = obj.properties;
        const textLength = this.readByte(propAddr);
        propAddr++;

        if (textLength === 0) return "";

        return this.decodeZString(propAddr);
    }

    // Object tree manipulation
    insertObject(objNum, destNum) {
        if (objNum === 0) return;

        // Remove from current parent
        this.removeObject(objNum);

        // Insert as first child of destination
        const dest = this.getObject(destNum);
        if (dest) {
            this.setObjectSibling(objNum, dest.child);
            this.setObjectChild(destNum, objNum);
            this.setObjectParent(objNum, destNum);
        }
    }

    removeObject(objNum) {
        if (objNum === 0) return;

        const obj = this.getObject(objNum);
        if (!obj || obj.parent === 0) return;

        const parent = this.getObject(obj.parent);
        if (!parent) return;

        // Remove from sibling chain
        if (parent.child === objNum) {
            // Object is first child
            this.setObjectChild(obj.parent, obj.sibling);
        } else {
            // Find previous sibling
            let prevSibling = parent.child;
            while (prevSibling !== 0) {
                const prevObj = this.getObject(prevSibling);
                if (prevObj.sibling === objNum) {
                    this.setObjectSibling(prevSibling, obj.sibling);
                    break;
                }
                prevSibling = prevObj.sibling;
            }
        }

        this.setObjectParent(objNum, 0);
        this.setObjectSibling(objNum, 0);
    }

    // Property access
    getPropertyAddr(objNum, propNum) {
        if (objNum === 0) return 0;

        const obj = this.getObject(objNum);
        if (!obj) return 0;

        let propAddr = obj.properties;
        const textLength = this.readByte(propAddr);
        propAddr += 1 + textLength * 2;

        // Search for property
        while (propAddr < this.memory.length) {
            const sizeByte = this.readByte(propAddr);
            if (sizeByte === 0) break;

            const num = sizeByte & 0x1F;
            if (num === propNum) {
                return propAddr + 1;
            }

            const size = (sizeByte >> 5) + 1;
            propAddr += 1 + size;
        }

        return 0;
    }

    getProperty(objNum, propNum) {
        const propAddr = this.getPropertyAddr(objNum, propNum);
        if (propAddr === 0) {
            // Return default property value
            const defaultAddr = OBJECT_TABLE_ADDR + (propNum - 1) * 2;
            return this.readWord(defaultAddr);
        }

        const sizeByte = this.readByte(propAddr - 1);
        const size = (sizeByte >> 5) + 1;

        if (size === 1) {
            return this.readByte(propAddr);
        } else {
            return this.readWord(propAddr);
        }
    }

    putProperty(objNum, propNum, value) {
        const propAddr = this.getPropertyAddr(objNum, propNum);
        if (propAddr === 0) return;

        const sizeByte = this.readByte(propAddr - 1);
        const size = (sizeByte >> 5) + 1;

        if (size === 1) {
            this.writeByte(propAddr, value);
        } else {
            this.writeWord(propAddr, value);
        }
    }

    getNextProperty(objNum, propNum) {
        if (objNum === 0) return 0;

        const obj = this.getObject(objNum);
        if (!obj) return 0;

        let propAddr = obj.properties;
        const textLength = this.readByte(propAddr);
        propAddr += 1 + textLength * 2;

        if (propNum === 0) {
            // Return first property
            const sizeByte = this.readByte(propAddr);
            return sizeByte & 0x1F;
        }

        // Search for property
        while (propAddr < this.memory.length) {
            const sizeByte = this.readByte(propAddr);
            if (sizeByte === 0) break;

            const num = sizeByte & 0x1F;
            const size = (sizeByte >> 5) + 1;

            if (num === propNum) {
                // Found current property, return next
                propAddr += 1 + size;
                const nextSizeByte = this.readByte(propAddr);
                return nextSizeByte & 0x1F;
            }

            propAddr += 1 + size;
        }

        return 0;
    }

    // Table scanning
    scanTable(value, tableAddr, length, form) {
        const fieldSize = form & 0x7F;
        const isWord = !(form & 0x80);

        for (let i = 0; i < length; i++) {
            const entryAddr = tableAddr + i * fieldSize;
            const entryValue = isWord ? this.readWord(entryAddr) : this.readByte(entryAddr);

            if (entryValue === value) {
                return entryAddr;
            }
        }

        return 0;
    }

    // Input handling
    read(textBuffer, parseBuffer) {
        if (this.debugMode) {
            console.error(`[READ] textBuffer=0x${textBuffer.toString(16)}, parseBuffer=0x${parseBuffer.toString(16)}`);
        }

        this.running = false;

        // Set up the input handler - will be called when input arrives
        const self = this;
        this.inputCallback = function(input) {
            if (self.debugMode) {
                console.error(`[INPUT] Received: "${input}"`);
            }

            // Store input in text buffer
            const maxLen = self.readByte(textBuffer);
            const actualLen = Math.min(input.length, maxLen);

            if (VERSION <= 4) {
                for (let i = 0; i < actualLen; i++) {
                    self.writeByte(textBuffer + 1 + i, input.toLowerCase().charCodeAt(i));
                }
                self.writeByte(textBuffer + 1 + actualLen, 0);
            } else {
                self.writeByte(textBuffer + 1, actualLen);
                for (let i = 0; i < actualLen; i++) {
                    self.writeByte(textBuffer + 2 + i, input.toLowerCase().charCodeAt(i));
                }
            }

            // Tokenize if parse buffer provided
            if (parseBuffer && parseBuffer !== 0) {
                self.tokenize(textBuffer, parseBuffer);
            }

            // Clear the callback and continue execution
            self.inputCallback = null;
            self.running = true;
            setTimeout(() => self.run(), 0);
        };
    }

    // Dictionary and tokenization
    tokenize(textBuffer, parseBuffer) {
        // DEBUG: Dump parse buffer BEFORE tokenization
        if (this.debugMode) {
            console.error(`[TOKENIZE] Parse buffer BEFORE (at 0x${parseBuffer.toString(16)}):`);
            console.error(`[TOKENIZE] Text buffer at 0x${textBuffer.toString(16)}`);

            // Show what's currently in the parse buffer
            for (let i = 0; i < 3; i++) {
                const entryAddr = parseBuffer + 2 + i * 4;
                const addr = this.readWord(entryAddr);
                const len = this.readByte(entryAddr + 2);
                const pos = this.readByte(entryAddr + 3);
                console.error(`[TOKENIZE]   Entry ${i}: addr=0x${addr.toString(16)}, len=${len}, pos=${pos}`);
            }
        }

        // Simplified tokenization
        let text;
        if (VERSION <= 4) {
            text = "";
            let addr = textBuffer + 1;
            let ch = this.readByte(addr);
            while (ch !== 0) {
                text += String.fromCharCode(ch);
                addr++;
                ch = this.readByte(addr);
            }
        } else {
            const len = this.readByte(textBuffer + 1);
            text = "";
            for (let i = 0; i < len; i++) {
                text += String.fromCharCode(this.readByte(textBuffer + 2 + i));
            }
        }

        // Split into words
        const words = text.trim().split(/\\s+/).filter(w => w.length > 0);
        const maxWords = this.readByte(parseBuffer);

        // Write number of words parsed
        this.writeByte(parseBuffer + 1, Math.min(words.length, maxWords));

        // Write each word entry
        let textPos = 0;  // Track position in original text
        for (let i = 0; i < Math.min(words.length, maxWords); i++) {
            const word = words[i];
            const dictAddr = this.lookupWord(word);

            if (this.debugMode) {
                console.error(`[TOKENIZE] Word ${i}: "${word}" -> dictAddr=0x${dictAddr.toString(16)}`);
            }

            // Find word position in text (1-indexed)
            const wordStart = text.indexOf(word, textPos);
            const position = wordStart + 1;  // 1-indexed position in text
            textPos = wordStart + word.length;

            // Write word entry: dict-addr (2 bytes), length (1 byte), position (1 byte)
            const entryAddr = parseBuffer + 2 + i * 4;
            this.writeWord(entryAddr, dictAddr);
            this.writeByte(entryAddr + 2, word.length);
            this.writeByte(entryAddr + 3, position);

            if (this.debugMode) {
                console.error(`[TOKENIZE]   Wrote to 0x${entryAddr.toString(16)}: addr=0x${dictAddr.toString(16)}, len=${word.length}, pos=${position}`);
            }
        }

        // DEBUG: Dump parse buffer contents
        if (this.debugMode) {
            console.error(`[TOKENIZE] Parse buffer dump (buffer starts at 0x${parseBuffer.toString(16)}):`);
            console.error(`[TOKENIZE]   Max words: ${this.readByte(parseBuffer)}`);
            console.error(`[TOKENIZE]   Num words: ${this.readByte(parseBuffer + 1)}`);
            const numWords = this.readByte(parseBuffer + 1);
            for (let i = 0; i < Math.max(numWords, 3); i++) {  // Show at least 3 entries
                const entryAddr = parseBuffer + 2 + i * 4;
                const addr = this.readWord(entryAddr);
                const len = this.readByte(entryAddr + 2);
                const pos = this.readByte(entryAddr + 3);
                console.error(`[TOKENIZE]   Entry ${i} at 0x${entryAddr.toString(16)}: addr=0x${addr.toString(16)}, len=${len}, pos=${pos}`);
            }
        }
    }

    lookupWord(word) {
        // Simplified dictionary lookup
        // Returns 0 if word not found
        const dict = DICTIONARY_ADDR;
        const numSeparators = this.readByte(dict);
        let addr = dict + 1 + numSeparators;

        const entryLength = this.readByte(addr);
        addr++;
        const numEntries = this.readWord(addr);
        addr += 2;

        // Encode the word using Z-string encoding
        const encoded = this.encodeWord(word);

        // Linear search through dictionary
        for (let i = 0; i < numEntries; i++) {
            const entryAddr = addr + i * entryLength;
            let match = true;

            for (let j = 0; j < Math.min(encoded.length, VERSION <= 3 ? 4 : 6); j++) {
                if (this.readByte(entryAddr + j) !== encoded[j]) {
                    match = false;
                    break;
                }
            }

            if (match) return entryAddr;
        }

        return 0;
    }

    encodeWord(word) {
        // Z-string encoding for dictionary words
        // V1-3 use 4 bytes (2 Z-chars per byte, 6 chars total)
        // V4+ use 6 bytes (9 chars total)
        const maxChars = VERSION <= 3 ? 6 : 9;
        const maxBytes = VERSION <= 3 ? 4 : 6;

        const alphabet = "abcdefghijklmnopqrstuvwxyz";
        const zchars = [];

        for (let i = 0; i < maxChars; i++) {
            if (i < word.length) {
                const ch = word[i].toLowerCase();
                const idx = alphabet.indexOf(ch);
                if (idx >= 0) {
                    zchars.push(idx + 6);  // A0 alphabet starts at 6
                } else {
                    zchars.push(5);  // Default to space character
                }
            } else {
                zchars.push(5);  // Pad with spaces
            }
        }

        // Pack Z-chars into bytes (3 Z-chars per 2-byte word)
        const bytes = [];
        for (let wordIdx = 0; wordIdx < maxBytes / 2; wordIdx++) {
            const z1 = zchars[wordIdx * 3] || 5;
            const z2 = zchars[wordIdx * 3 + 1] || 5;
            const z3 = zchars[wordIdx * 3 + 2] || 5;

            let word = (z1 << 10) | (z2 << 5) | z3;

            // Set top bit on last word only
            if (wordIdx === (maxBytes / 2) - 1) {
                word |= 0x8000;
            }

            bytes.push((word >> 8) & 0xFF);
            bytes.push(word & 0xFF);
        }

        return bytes;
    }
}'''

    def _generate_memory(self) -> str:
        """Generate memory initialization"""
        # Encode story data as base64
        story_b64 = base64.b64encode(self.parser.data).decode('ascii')

        # Split into chunks for readability
        chunks = [story_b64[i:i+76] for i in range(0, len(story_b64), 76)]
        story_str = '",\n    "'.join(chunks)

        return f'''// Story Data (Base64 encoded)
const STORY_DATA_BASE64 = [
    "{story_str}"
].join("");

// Decode base64 to Uint8Array
function decodeStoryData() {{
    if (typeof atob !== "undefined") {{
        // Browser
        const binary = atob(STORY_DATA_BASE64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {{
            bytes[i] = binary.charCodeAt(i);
        }}
        return bytes;
    }} else {{
        // Node.js
        return new Uint8Array(Buffer.from(STORY_DATA_BASE64, "base64"));
    }}
}}'''

    def _generate_opcodes(self) -> str:
        """Generate opcode implementation"""
        return '''// Opcode Implementations
ZMachine.prototype.executeInstruction = function() {
    const instrPC = this.pc;
    const opcode = this.readByte(this.pc);
    this.pc++;

    // Add comprehensive debug logging matching frotz output format
    if (this.debugMode) {
        // Get local variables from current frame
        const l1 = this.locals[0] || 0;
        const l2 = this.locals[1] || 0;
        const l3 = this.locals[2] || 0;
        const l4 = this.locals[3] || 0;
        const l5 = this.locals[4] || 0;

        console.error(`[STEP ${this.instructionCount}] PC=0x${instrPC.toString(16).padStart(4, '0')} Op=0x${opcode.toString(16).padStart(2, '0')} L1=0x${l1.toString(16).padStart(4, '0')} L2=0x${l2.toString(16).padStart(4, '0')} L3=0x${l3.toString(16).padStart(4, '0')} L4=0x${l4.toString(16).padStart(4, '0')} L5=0x${l5.toString(16).padStart(4, '0')}`);
    }

    // Decode instruction form
    if (opcode === 0xBE && VERSION >= 5) {
        return this.executeExtended();
    } else if ((opcode & 0xC0) === 0xC0) {
        // Variable form
        if (opcode < 0xE0) {
            return this.execute2OPVar(opcode & 0x1F);
        } else {
            return this.executeVAR(opcode & 0x1F);
        }
    } else if ((opcode & 0x80) === 0x80) {
        // Short form
        const operandType = (opcode >> 4) & 0x03;
        const opcodeNum = opcode & 0x0F;

        if (operandType === 0x03) {
            return this.execute0OP(opcodeNum);
        } else {
            let operand;
            if (operandType === 0x00) {
                operand = this.readWord(this.pc);
                this.pc += 2;
            } else if (operandType === 0x01) {
                operand = this.readByte(this.pc);
                this.pc++;
            } else {
                operand = ["var", this.readByte(this.pc)];
                this.pc++;
            }
            return this.execute1OP(opcodeNum, operand);
        }
    } else {
        // Long form
        const opcodeNum = opcode & 0x1F;
        const op1 = (opcode & 0x40) ? ["var", this.readByte(this.pc)] : this.readByte(this.pc);
        this.pc++;
        const op2 = (opcode & 0x20) ? ["var", this.readByte(this.pc)] : this.readByte(this.pc);
        this.pc++;
        return this.execute2OP(opcodeNum, op1, op2);
    }
};

// 0OP Instructions
ZMachine.prototype.execute0OP = function(opcode) {
    switch (opcode) {
        case 0x00: // rtrue
            this.returnFromRoutine(1);
            break;
        case 0x01: // rfalse
            this.returnFromRoutine(0);
            break;
        case 0x02: // print
            this.printLiteral();
            break;
        case 0x03: // print_ret
            this.printLiteral();
            this.newLine();
            this.returnFromRoutine(1);
            break;
        case 0x08: // ret_popped
            {
                const value = this.pop();
                this.returnFromRoutine(value);
            }
            break;
        case 0x0A: // quit
            this.quit();
            break;
        case 0x0B: // new_line
            this.newLine();
            break;
        case 0x0D: // verify
            this.branch(true); // Always succeed for now
            break;
        default:
            throw new Error(`Unimplemented 0OP opcode: 0x${opcode.toString(16)}`);
    }
};

// 1OP Instructions
ZMachine.prototype.execute1OP = function(opcode, operand) {
    const value = this.getOperand(operand);

    switch (opcode) {
        case 0x00: // jz
            this.branch(value === 0);
            break;
        case 0x01: // get_sibling
            {
                const obj = this.getObject(value);
                const sibling = obj ? obj.sibling : 0;
                this.store(sibling);
                this.branch(sibling !== 0);
            }
            break;
        case 0x02: // get_child
            {
                const obj = this.getObject(value);
                const child = obj ? obj.child : 0;
                this.store(child);
                this.branch(child !== 0);
            }
            break;
        case 0x03: // get_parent
            {
                const obj = this.getObject(value);
                this.store(obj ? obj.parent : 0);
            }
            break;
        case 0x04: // get_prop_len
            {
                const propAddr = value;
                if (propAddr === 0) {
                    this.store(0);
                } else {
                    const sizeByte = this.readByte(propAddr - 1);
                    this.store((sizeByte >> 5) + 1);
                }
            }
            break;
        case 0x05: // inc
            {
                const varNum = value;
                const val = this.getVariable(varNum);
                this.setVariable(varNum, val + 1);
            }
            break;
        case 0x06: // dec
            {
                const varNum = value;
                const val = this.getVariable(varNum);
                this.setVariable(varNum, val - 1);
            }
            break;
        case 0x07: // print_addr
            {
                const addr = value;
                const text = this.decodeZString(addr);
                this.print(text);
            }
            break;
        case 0x08: // call_1s (V4+)
            if (VERSION >= 4) {
                const storeVar = this.readByte(this.pc);
                this.pc++;
                this.callRoutine(value, [], storeVar);
            }
            break;
        case 0x09: // remove_obj
            {
                const objNum = value;
                const obj = this.getObject(objNum);
                if (obj && obj.parent) {
                    const parent = this.getObject(obj.parent);
                    if (parent) {
                        // Remove from parent's child list
                        if (parent.child === objNum) {
                            this.setObjectChild(obj.parent, obj.sibling);
                        } else {
                            // Find in sibling chain
                            let prev = parent.child;
                            while (prev) {
                                const prevObj = this.getObject(prev);
                                if (prevObj && prevObj.sibling === objNum) {
                                    this.setObjectSibling(prev, obj.sibling);
                                    break;
                                }
                                prev = prevObj ? prevObj.sibling : 0;
                            }
                        }
                    }
                    this.setObjectParent(objNum, 0);
                    this.setObjectSibling(objNum, 0);
                }
            }
            break;
        case 0x0A: // print_obj
            {
                const name = this.getObjectName(value);
                this.print(name);
            }
            break;
        case 0x0B: // ret
            this.returnFromRoutine(value);
            break;
        case 0x0C: // jump
            {
                // Sign extend 16-bit value
                let offset = value;
                if (offset > 32767) offset -= 65536;
                this.pc += offset - 2;
            }
            break;
        case 0x0D: // print_paddr
            {
                const addr = this.unpackAddress(value, true);
                const text = this.decodeZString(addr);
                this.print(text);
            }
            break;
        case 0x0E: // load
            {
                const varNum = value;
                if (this.debugMode && this.instructionCount < 20) {
                    console.error(`  LOAD from var ${varNum} (stack size: ${this.stack.length})`);
                }
                const val = this.getVariable(varNum);
                this.store(val);
            }
            break;
        case 0x0F: // not (V4) / call_1n (V5+)
            if (VERSION >= 5) {
                // call_1n
                this.callRoutine(value, [], null);
            } else if (VERSION >= 4) {
                // not (bitwise complement)
                this.store(~value & 0xFFFF);
            }
            break;
        default:
            throw new Error(`Unimplemented 1OP opcode: 0x${opcode.toString(16)}`);
    }
};

// 2OP Instructions (Long form)
ZMachine.prototype.execute2OP = function(opcode, operand1, operand2) {
    const val1 = this.getOperand(operand1);
    const val2 = this.getOperand(operand2);

    switch (opcode) {
        case 0x00: // Illegal opcode - reserved
            // This should never be encountered in valid Z-code
            // If we hit this, something is very wrong with our implementation
            throw new Error(`Illegal 2OP opcode 0x00 encountered at PC 0x${(this.pc - 3).toString(16)} - this indicates a serious bug in instruction decoding or PC management`);
        case 0x01: // je (jump if equal)
            this.branch(val1 === val2);
            break;
        case 0x02: // jl (jump if less than - signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                this.branch(a < b);
            }
            break;
        case 0x03: // jg (jump if greater than - signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                this.branch(a > b);
            }
            break;
        case 0x04: // dec_chk
            {
                const varNum = val1;
                const currentVal = this.getVariable(varNum);
                const newVal = (currentVal - 1) & 0xFFFF;
                this.setVariable(varNum, newVal);
                const signedNew = newVal > 32767 ? newVal - 65536 : newVal;
                const signedCheck = val2 > 32767 ? val2 - 65536 : val2;
                this.branch(signedNew < signedCheck);
            }
            break;
        case 0x05: // inc_chk
            {
                const varNum = val1;
                const currentVal = this.getVariable(varNum);
                const newVal = (currentVal + 1) & 0xFFFF;
                this.setVariable(varNum, newVal);
                const signedNew = newVal > 32767 ? newVal - 65536 : newVal;
                const signedCheck = val2 > 32767 ? val2 - 65536 : val2;
                this.branch(signedNew > signedCheck);
            }
            break;
        case 0x06: // jin (jump if object is in another object)
            {
                const obj1 = this.getObject(val1);
                this.branch(obj1 && obj1.parent === val2);
            }
            break;
        case 0x07: // test (test bitmap)
            this.branch((val1 & val2) === val2);
            break;
        case 0x08: // or
            this.store(val1 | val2);
            break;
        case 0x09: // and
            this.store(val1 & val2);
            break;
        case 0x0A: // test_attr
            this.branch(this.testAttribute(val1, val2));
            break;
        case 0x0B: // set_attr
            this.setAttribute(val1, val2);
            break;
        case 0x0C: // clear_attr
            this.clearAttribute(val1, val2);
            break;
        case 0x0D: // store (variable)
            this.setVariable(val1, val2);
            break;
        case 0x0E: // insert_obj
            this.insertObject(val1, val2);
            break;
        case 0x0F: // loadw (load word from array)
            {
                const addr = val1 + 2 * val2;
                this.store(this.readWord(addr));
            }
            break;
        case 0x10: // loadb (load byte from array)
            {
                const addr = val1 + val2;
                this.store(this.readByte(addr));
            }
            break;
        case 0x11: // get_prop
            this.store(this.getProperty(val1, val2));
            break;
        case 0x12: // get_prop_addr
            this.store(this.getPropertyAddr(val1, val2));
            break;
        case 0x13: // get_next_prop
            this.store(this.getNextProperty(val1, val2));
            break;
        case 0x14: // add (signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                let result = a + b;
                if (result < -32768) result += 65536;
                if (result > 32767) result -= 65536;
                this.store(result < 0 ? result + 65536 : result);
            }
            break;
        case 0x15: // sub (signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                let result = a - b;
                if (result < -32768) result += 65536;
                if (result > 32767) result -= 65536;
                this.store(result < 0 ? result + 65536 : result);
            }
            break;
        case 0x16: // mul (signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                let result = a * b;
                while (result < -32768) result += 65536;
                while (result > 32767) result -= 65536;
                this.store(result < 0 ? result + 65536 : result);
            }
            break;
        case 0x17: // div (signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                if (b === 0) throw new Error("Division by zero");
                const result = Math.trunc(a / b);
                this.store(result < 0 ? result + 65536 : result);
            }
            break;
        case 0x18: // mod (signed)
            {
                const a = val1 > 32767 ? val1 - 65536 : val1;
                const b = val2 > 32767 ? val2 - 65536 : val2;
                if (b === 0) throw new Error("Division by zero");
                const result = a % b;
                this.store(result < 0 ? result + 65536 : result);
            }
            break;
        case 0x19: // call_2s (V4+)
            if (VERSION >= 4) {
                this.callRoutine(val1, [val2], this.readByte(this.pc));
                this.pc++;
            }
            break;
        case 0x1A: // call_2n (V5+)
            if (VERSION >= 5) {
                this.callRoutine(val1, [val2], null);
            }
            break;
        case 0x1B: // set_colour (V5+)
            // Not implemented - no-op
            break;
        case 0x1C: // throw (V5+)
            // Not implemented
            break;
        default:
            throw new Error(`Unimplemented 2OP opcode: 0x${opcode.toString(16)}`);
    }
};

// 2OP Instructions (Variable form) - reads operands and redirects to execute2OP
// Note: Some 2OP instructions like 'je' can take more than 2 operands in variable form!
ZMachine.prototype.execute2OPVar = function(opcode) {
    // Read operand types
    const types = this.readByte(this.pc);
    this.pc++;

    const operands = [];
    // Read up to 4 operands (je and some others can use all 4)
    for (let i = 0; i < 4; i++) {
        const opType = (types >> (6 - i * 2)) & 0x03;
        if (opType === 3) break; // No more operands
        if (opType === 0) {
            operands.push(this.readWord(this.pc));
            this.pc += 2;
        } else if (opType === 1) {
            operands.push(this.readByte(this.pc));
            this.pc++;
        } else if (opType === 2) {
            operands.push(["var", this.readByte(this.pc)]);
            this.pc++;
        }
    }

    // For je opcode (0x01), handle multiple operands specially
    if (opcode === 0x01 && operands.length > 2) {
        // je with more than 2 operands: check if first equals any of the rest
        const val1 = this.getOperand(operands[0]);
        let result = false;
        for (let i = 1; i < operands.length; i++) {
            if (val1 === this.getOperand(operands[i])) {
                result = true;
                break;
            }
        }
        this.branch(result);
        return;
    }

    // For other 2OP instructions, just use first 2 operands
    return this.execute2OP(opcode, operands[0], operands[1]);
};

// VAR Instructions
ZMachine.prototype.executeVAR = function(opcode) {
    // Read operand types
    const types = this.readByte(this.pc);
    this.pc++;

    const operands = [];
    for (let i = 0; i < 4; i++) {
        const opType = (types >> (6 - i * 2)) & 0x03;
        if (opType === 3) break; // No more operands
        if (opType === 0) {
            operands.push(this.readWord(this.pc));
            this.pc += 2;
        } else if (opType === 1) {
            operands.push(this.readByte(this.pc));
            this.pc++;
        } else if (opType === 2) {
            operands.push(["var", this.readByte(this.pc)]);
            this.pc++;
        }
    }

    // Get actual values
    const values = operands.map(op => this.getOperand(op));

    if (this.debugMode && this.instructionCount < 20 && (opcode === 0x00 || opcode === 0x01)) {
        console.error(`  -> VAR operand types: 0x${types.toString(16)}, operands:`, operands, 'values:', values);
    }

    switch (opcode) {
        case 0x00: // call (call routine with 0-3 args)
            {
                const packedAddr = values[0];
                const args = values.slice(1);
                const storeVar = this.readByte(this.pc);
                this.pc++;
                if (this.debugMode && this.instructionCount < 20) {
                    console.error(`  CALL routine 0x${packedAddr.toString(16)} with args [${args.map(a => '0x' + a.toString(16)).join(', ')}] store to var ${storeVar}`);
                }
                this.callRoutine(packedAddr, args, storeVar);
            }
            break;
        case 0x01: // storew
            this.writeWord(values[0] + 2 * values[1], values[2]);
            break;
        case 0x02: // storeb
            {
                const addr = values[0] + values[1];
                this.writeByte(addr, values[2]);
            }
            break;
        case 0x03: // put_prop
            this.putProperty(values[0], values[1], values[2]);
            break;
        case 0x04: // read (sread in V5+)
            if (this.debugMode) {
                console.error(`[VAR 0x04 READ] Called with values[0]=0x${values[0].toString(16)}, values[1]=0x${values[1].toString(16)}`);
            }
            this.read(values[0], values[1]);
            break;
        case 0x05: // print_char
            this.printChar(values[0]);
            break;
        case 0x06: // print_num
            this.printNum(values[0]);
            break;
        case 0x07: // random
            {
                const result = this.random(values[0]);
                this.store(result);
            }
            break;
        case 0x08: // push
            this.push(values[0]);
            break;
        case 0x09: // pull
            {
                const value = this.pop();
                this.setVariable(values[0], value);
            }
            break;
        case 0x0A: // split_window (V3+)
            // Not implemented - no-op
            break;
        case 0x0B: // set_window (V3+)
            this.currentWindow = values[0];
            break;
        case 0x0D: // call_vs2 (V4+)
            if (VERSION >= 4) {
                const packedAddr = values[0];
                const args = values.slice(1);
                const storeVar = this.readByte(this.pc);
                this.pc++;
                this.callRoutine(packedAddr, args, storeVar);
            }
            break;
        case 0x0E: // erase_window (V4+)
            // Not implemented - no-op
            break;
        case 0x0F: // erase_line (V4+)
            // Not implemented - no-op
            break;
        case 0x10: // set_cursor (V4+)
            // Not implemented - no-op
            break;
        case 0x11: // get_cursor (V4+)
            // Not implemented - no-op
            break;
        case 0x12: // set_text_style (V4+)
            // Not implemented - no-op
            break;
        case 0x13: // buffer_mode (V4+)
            // Not implemented - no-op
            break;
        case 0x14: // output_stream
            // Not implemented - no-op
            break;
        case 0x15: // input_stream
            // Not implemented - no-op
            break;
        case 0x16: // sound_effect
            // Not implemented - no-op
            break;
        case 0x17: // read_char (V4+)
            // Would need async input
            this.store(13); // Return newline for now
            break;
        case 0x18: // scan_table (V4+)
            {
                const result = this.scanTable(values[0], values[1], values[2], values[3] || 0x82);
                this.store(result);
                this.branch(result !== 0);
            }
            break;
        case 0x19: // not (bitwise not)
            this.store(~values[0] & 0xFFFF);
            break;
        case 0x1A: // call_vn (V5+)
            if (VERSION >= 5) {
                this.callRoutine(values[0], values.slice(1), null);
            }
            break;
        case 0x1B: // call_vn2 (V5+)
            if (VERSION >= 5) {
                this.callRoutine(values[0], values.slice(1), null);
            }
            break;
        case 0x1C: // tokenise (V5+)
            // Not implemented - no-op
            break;
        case 0x1D: // encode_text (V5+)
            // Not implemented - no-op
            break;
        case 0x1E: // copy_table (V5+)
            // Not implemented - no-op
            break;
        case 0x1F: // print_table (V5+)
            // Not implemented - no-op
            break;
        default:
            throw new Error(`Unimplemented VAR opcode: 0x${opcode.toString(16)}`);
    }
};

// Helper functions
ZMachine.prototype.printLiteral = function() {
    const text = this.decodeZString(this.pc);
    this.print(text);
    // Skip past the Z-string (which uses 2-byte words)
    // The high bit of each word indicates if it's the last word
    let addr = this.pc;
    while (true) {
        const word = this.readWord(addr);
        addr += 2;
        if (word & 0x8000) {
            // This was the last word
            break;
        }
    }
    this.pc = addr;
};

ZMachine.prototype.branch = function(condition) {
    // Save the address of the branch data for offset calculation
    const branchDataAddr = this.pc;
    const branchByte = this.readByte(this.pc);
    this.pc++;

    const branchOnTrue = !!(branchByte & 0x80);
    let offset;
    let offsetSize;

    if (branchByte & 0x40) {
        // Short form (6-bit offset)
        offset = branchByte & 0x3F;
        offsetSize = 1;  // 1 byte total
    } else {
        // Long form (14-bit signed offset)
        const secondByte = this.readByte(this.pc);
        offset = ((branchByte & 0x3F) << 8) | secondByte;
        this.pc++;
        offsetSize = 2;  // 2 bytes total

        if (offset & 0x2000) {
            offset |= 0xC000; // Sign extend
        }
        // Convert to signed
        if (offset > 32767) offset -= 65536;
    }

    if (condition === branchOnTrue) {
        if (offset === 0) {
            this.returnFromRoutine(0);
        } else if (offset === 1) {
            this.returnFromRoutine(1);
        } else {
            // Offset is relative to the address AFTER the branch data
            // The offset of 2 means "branch to the instruction immediately after this one"
            // So we calculate: (address of branch data) + (size of branch data) + (offset) - 2
            const newPC = branchDataAddr + offsetSize + offset - 2;

            // Safety check: don't branch to header area (first 64 bytes)
            if (newPC < 0x40) {
                if (this.debugMode) {
                    console.error(`[BRANCH] WARNING: Attempted to branch to 0x${newPC.toString(16)} which is in the header`);
                    console.error(`[BRANCH] This usually indicates a bug in parsing or variable handling`);
                    console.error(`[BRANCH] Branch from 0x${branchDataAddr.toString(16)} with offset ${offset}`);
                    console.error(`[BRANCH] This is likely a parse error - returning 0 to indicate failure`);
                }
                // Treat this as a catastrophic error and return false from the routine
                this.returnFromRoutine(0);
            } else {
                this.pc = newPC;
            }
        }
    }
};

ZMachine.prototype.store = function(value) {
    const varNum = this.readByte(this.pc);
    this.pc++;
    this.setVariable(varNum, value);
};

ZMachine.prototype.returnFromRoutine = function(value) {
    if (this.callStack.length === 0) {
        this.quit();
        return;
    }

    const frame = this.callStack.pop();

    this.pc = frame.returnPC;
    this.locals = frame.locals;

    if (frame.storeVar !== null) {
        this.setVariable(frame.storeVar, value);
    }
};

ZMachine.prototype.getObjectName = function(objNum) {
    const obj = this.getObject(objNum);
    if (!obj) return "";

    let propAddr = obj.properties;
    const textLength = this.readByte(propAddr);
    propAddr++;

    if (textLength === 0) return "";

    return this.decodeZString(propAddr);
};'''

    def _generate_routines(self) -> str:
        """Generate discovered routines"""
        return '''// Routine call handling
ZMachine.prototype.callRoutine = function(packedAddr, args, storeVar) {
    if (packedAddr === 0) {
        if (storeVar !== null) {
            this.setVariable(storeVar, 0);
        }
        return;
    }

    const addr = this.unpackAddress(packedAddr);

    // Sanity check - routine address should be at least in static memory region
    if (addr < STATIC_MEMORY) {
        console.warn(`Warning: Attempted to call routine at invalid address 0x${addr.toString(16)} (packed: 0x${packedAddr.toString(16)})`);
        if (storeVar !== null) {
            this.setVariable(storeVar, 0);
        }
        return;
    }

    // Read routine header
    const numLocals = this.readByte(addr);

    if (this.debugMode && this.instructionCount < 20) {
        console.error(`  -> Unpacked to addr 0x${addr.toString(16)}, numLocals=${numLocals}`);
    }

    // Sanity check - Z-Machine routines can have at most 15 locals
    if (numLocals > 15) {
        throw new Error(`Invalid routine at 0x${addr.toString(16)} (packed: 0x${packedAddr.toString(16)}): numLocals=${numLocals} exceeds maximum of 15`);
    }

    // Save current state (make a copy of locals array!)

    this.callStack.push({
        returnPC: this.pc,
        locals: this.locals.slice(),
        numLocals: numLocals,
        storeVar: storeVar
    });

    // Initialize new locals
    this.locals = new Array(16);

    // Set up locals
    if (VERSION <= 4) {
        // Read default local values
        for (let i = 0; i < numLocals; i++) {
            this.locals[i] = this.readWord(addr + 1 + i * 2);
        }
        this.pc = addr + 1 + numLocals * 2;
    } else {
        // V5+ - locals start at 0
        for (let i = 0; i < numLocals; i++) {
            this.locals[i] = 0;
        }
        this.pc = addr + 1;
    }

    // Copy arguments to locals
    if (this.debugMode) {
        console.error(`[CALL ${this.instructionCount}] To addr 0x${addr.toString(16)}: numLocals=${numLocals}, args=[${args.map(a => '0x'+a.toString(16)).join(', ')}]`);
        console.error(`[CALL ${this.instructionCount}] Defaults: ${this.locals.slice(0, numLocals).map((v,i) => `L${i+1}=0x${v.toString(16)}`).join(' ')}`);
    }
    for (let i = 0; i < args.length && i < numLocals; i++) {
        this.locals[i] = args[i];
    }
    if (this.debugMode) {
        console.error(`[CALL ${this.instructionCount}] Final:    ${this.locals.slice(0, numLocals).map((v,i) => `L${i+1}=0x${v.toString(16)}`).join(' ')}`);
    }
};'''

    def _generate_main(self) -> str:
        """Generate main execution loop"""
        return '''// Crash dump generation
ZMachine.prototype.generateCrashDump = function(error) {
    const dump = {
        timestamp: new Date().toISOString(),
        error: {
            message: error.message,
            stack: error.stack,
            name: error.name
        },
        machine: {
            version: VERSION,
            pc: `0x${this.pc.toString(16)}`,
            instructionCount: this.instructionCount,
            running: this.running,
            finished: this.finished
        },
        memory: {
            staticMemoryStart: `0x${STATIC_MEMORY.toString(16)}`,
            highMemoryStart: `0x${HIGH_MEMORY.toString(16)}`,
            pcBytes: Array.from(this.memory.slice(Math.max(0, this.pc - 10), this.pc + 20)).map(b => `0x${b.toString(16).padStart(2, '0')}`)
        },
        stack: {
            evaluationStack: this.stack.slice(-20).map(v => `0x${v.toString(16)}`),
            stackDepth: this.stack.length,
            callStack: this.callStack.map((frame, i) => ({
                frameNumber: i,
                returnPC: `0x${frame.returnPC.toString(16)}`,
                numLocals: frame.numLocals,
                storeVar: frame.storeVar,
                locals: frame.locals.slice(0, frame.numLocals).map(v => v === undefined ? 'undefined' : `0x${v.toString(16)}`)
            })),
            callDepth: this.callStack.length
        },
        locals: this.locals.map((v, i) => v === undefined ? undefined : `0x${v.toString(16)}`),
        globals: {
            sample: Array.from({length: 10}, (_, i) => {
                const addr = GLOBALS_ADDR + i * 2;
                return `g${i.toString().padStart(3, '0')}: 0x${this.readWord(addr).toString(16).padStart(4, '0')}`;
            })
        },
        instructionHistory: this.instructionHistory,
        output: {
            buffer: this.outputBuffer.substring(Math.max(0, this.outputBuffer.length - 500)),
            totalLength: this.outputBuffer.length
        }
    };

    return dump;
};

ZMachine.prototype.saveCrashDump = function(dump) {
    const json = JSON.stringify(dump, null, 2);

    if (typeof window !== "undefined" && typeof document !== "undefined") {
        // Browser environment - offer download
        const blob = new Blob([json], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `zmachine-crash-${Date.now()}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        console.error('Crash dump saved to downloads');
    } else if (typeof require !== "undefined") {
        // Node.js environment
        try {
            const fs = require('fs');
            const filename = `zmachine-crash-${Date.now()}.json`;
            fs.writeFileSync(filename, json);
            console.error(`Crash dump saved to ${filename}`);
        } catch (e) {
            console.error('Failed to save crash dump:', e.message);
            console.error('Crash dump:', json);
        }
    } else {
        console.error('Crash dump:', json);
    }
};

ZMachine.prototype.recordInstruction = function(pc, opcode) {
    if (!this.debugMode) return;

    const record = {
        count: this.instructionCount,
        pc: `0x${pc.toString(16)}`,
        opcode: `0x${opcode.toString(16)}`,
        stackDepth: this.stack.length,
        callDepth: this.callStack.length
    };

    this.instructionHistory.push(record);
    if (this.instructionHistory.length > this.maxHistorySize) {
        this.instructionHistory.shift();
    }
};

// Main execution loop
ZMachine.prototype.run = function() {
    const entryPC = this.pc;
    const entryStack = this.stack.length;
    const entryInst = this.instructionCount;
    this.running = true;
    if (this.debugMode) {
        console.error(`[RUN] Entry: PC=0x${entryPC.toString(16)} stack=${entryStack} inst=${entryInst}`);
    }

    while (this.running && !this.finished) {
        try {
            const currentPC = this.pc;
            const opcode = this.readByte(this.pc);

            if (this.debugMode) {
                this.recordInstruction(currentPC, opcode);
                this.instructionCount++;
            }

            this.executeInstruction();

            // Safety check - detect infinite loops
            if (this.debugMode && this.instructionCount > 100000) {
                throw new Error(`Instruction count exceeded 100000 - possible infinite loop`);
            }

        } catch (e) {
            console.error(`\\n========== Z-MACHINE CRASH ==========`);
            console.error(`Error at PC 0x${this.pc.toString(16)}: ${e.message}`);
            console.error(`Instruction count: ${this.instructionCount}`);
            console.error(`Call depth: ${this.callStack.length}`);
            console.error(`Stack depth: ${this.stack.length}`);
            console.error(`=====================================\\n`);

            if (this.debugMode) {
                const dump = this.generateCrashDump(e);
                this.saveCrashDump(dump);
                console.error('Full crash dump has been saved');
            }

            console.error('\\nStack trace:', e.stack);
            this.running = false;
            break;
        }

        // Yield periodically for UI updates
        if (this.instructionCount % 1000 === 0 && typeof window !== "undefined") {
            setTimeout(() => this.run(), 0);
            return;
        }
    }

    if (this.finished) {
        console.error('\\n[Z-Machine execution completed]');
    } else if (!this.running) {
        console.error('\\n[Z-Machine execution stopped]');
    }
};

// Initialize and start the Z-Machine
function createZMachine() {
    const storyData = decodeStoryData();
    return new ZMachine(storyData);
}'''

    def _generate_exports(self) -> str:
        """Generate module exports"""
        return '''// Module exports
if (typeof module !== "undefined" && module.exports) {
    // Node.js
    module.exports = {
        ZMachine,
        createZMachine,
        VERSION,
        decodeStoryData
    };

    // Auto-run if executed directly (not required as a module)
    if (require.main === module) {
        console.error('Starting Z-Machine game...\\n');
        const readline = require('readline');
        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });

        const m = createZMachine();

        // Check for --debug flag
        if (process.argv.includes('--debug')) {
            m.debugMode = true;
            console.error('[DEBUG MODE ENABLED]\\n');
        }

        // Output handler
        m.outputCallback = (text) => {
            process.stdout.write(text);
        };

        // Input handler will be set by read() opcode when needed
        m.inputCallback = null;

        // Input polling function
        function checkForInput() {
            if (m.inputCallback && !m.running) {
                // Game is waiting for input
                rl.question('\\n> ', (answer) => {
                    if (m.inputCallback) {
                        m.inputCallback(answer);
                        // Check again after execution
                        setTimeout(checkForInput, 10);
                    }
                });
            } else if (m.finished) {
                // Game is done
                rl.close();
            } else if (!m.running) {
                // Check again soon
                setTimeout(checkForInput, 10);
            } else {
                // Still running, check again
                setTimeout(checkForInput, 10);
            }
        }

        // Start the game
        try {
            m.run();
            // Start polling for input
            setTimeout(checkForInput, 10);
        } catch (e) {
            console.error('Fatal error:', e.message);
            console.error(e.stack);
            rl.close();
            process.exit(1);
        }
    }
} else if (typeof define === "function" && define.amd) {
    // AMD
    define([], function() {
        return {
            ZMachine,
            createZMachine,
            VERSION,
            decodeStoryData
        };
    });
} else {
    // Browser global
    window.ZMachine = ZMachine;
    window.createZMachine = createZMachine;
}'''


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 3:
        print("Usage: python jsgen.py <story_file.z3> <output.js>")
        sys.exit(1)

    story_file = sys.argv[1]
    output_file = sys.argv[2]

    # Read and parse the story file
    with open(story_file, 'rb') as f:
        data = f.read()

    parser = ZParser(data)

    # Generate JavaScript
    generator = JavaScriptGenerator(parser)
    js_code = generator.generate()

    # Write output
    with open(output_file, 'w') as f:
        f.write(js_code)

    print(f"Generated {output_file} from {story_file}")